##访问相关配置
#server.port=8082
#server.tomcat.uri-encoding=UTF-8
##项目访问名称，如果不配置直接访问bean就可以
##server.servlet.context-path=/restful
#
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jspspringboot mybatis 无映射到xml文件
##静态文件访问配置
#
##spring.resources.static-locations=classpath:static/
##spring.mvc.static-path-pattern=/**
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 30m

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/library?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 666
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 300
    jedis:
      pool:
        max-wait: -1
        max-idle: 8
        min-idle: 0


mybatis:
  type-aliases-package: com.test.restful.domain
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true